[package]
name = "fugue-concolic"
version = "0.1.8"
edition = "2018"

[features]
loader-all = ["fuguex/loader-all"]
loader-binaryninja = ["fuguex/loader-binaryninja"]
loader-ghidra = ["fuguex/loader-ghidra"]
loader-idapro = ["fuguex/loader-idapro"]
loader-radare = ["fuguex/loader-radare"]

solver-boolector = ["boolector"]
solver-static-boolector = ["solver-boolector", "boolector/vendor-lgl"]

solver-z3 = ["z3"]
solver-static-z3 = ["solver-z3", "z3/static-link-z3"]

default = ["solver-static-boolector"]

[dependencies]
boolector = { version = "0.4.2", registry = "fugue", optional = true }
disjoint-interval-tree = { version = "0.1", registry = "fugue" }
dyn-clone = "1"
either = "1"
fnv = "1"
fugue = { version = "0.2", registry = "fugue" }
fugue-static = { version = "0.2", registry = "fugue" }
fuguex = { version = "0.2", registry = "fugue" }
fxhash = "0.2"
hashconsing = "1"
itertools = "0.10"
log = "0.4"
parking_lot = "0.11"
smallvec = "1"
thiserror = "1"
z3 = { version = "0.11", optional = true }
