[package]
name = "fugue-concolic"
version = "0.1.4"
edition = "2018"

[features]
loader-all = ["fuguex/loader-all"]
loader-binaryninja = ["fuguex/loader-binaryninja"]
loader-ghidra = ["fuguex/loader-ghidra"]
loader-idapro = ["fuguex/loader-idapro"]
loader-radare = ["fuguex/loader-radare"]

shared-boolector = ["boolector-sys"]
static-boolector = ["boolector-sys/vendor-lgl"]

[dependencies]
boolector = "0.4"
boolector-sys = { version = "0.6.3", optional = true }
disjoint-interval-tree = { version = "0.1", registry = "fugue" }
dyn-clone = "1"
either = "1"
fnv = "1"
fugue = { version = "0.2", registry = "fugue" }
fugue-static = { version = "0.2", registry = "fugue" }
fuguex = { version = "0.2", registry = "fugue" }
fxhash = "0.2"
hashconsing = "1"
itertools = "0.10"
log = "0.4"
parking_lot = "0.11"
smallvec = "1"
thiserror = "1"
