[package]
name = "fugue-concolic"
version = "0.2.4"
edition = "2021"
description = "Concolic execution Engine for Fugue"
license = "MIT"
repository = "https://github.com/fugue-re/fugue-concolic"

[features]
loader-all = ["fuguex/loader-all"]
loader-ghidra = ["fuguex/loader-ghidra"]
loader-idapro = ["fuguex/loader-idapro"]
loader-radare = ["fuguex/loader-radare"]

[dependencies]
dyn-clone = "1"
either = "1"
fnv = "1"
fugue = { version = "0.2", registry = "fugue", default-features = false }
fuguex = { version = "0.2", registry = "fugue", default-features = false }
fxhash = "0.2"
hashconsing = "1"
intervals = { version = "0.1", registry = "fugue" }
itertools = "0.10"
parking_lot = "0.11"
smallvec = "1"
thiserror = "1"
